version: "3.8"

services:
  # Next.js app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

  # Jenkins avec Docker CLI
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: custom-jenkins-docker
    container_name: jenkins-ci
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
